on: [push]

jobs:
  mrsk_deploy_job:
    runs-on: ubuntu-latest
    name: A job to deploy web apps  
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: pwd 
      - run: ls -al .ssh 

      # - name: MRSK help command
      #   uses: ./
      # - name: MRSK version command
      #   uses: ./
      #   with: 
      #     args: version
