on: [push]

jobs:
  mrsk_deploy_job:
    runs-on: ubuntu-latest
    name: A job to deploy web apps  
    steps:
      - uses: actions/checkout@v3
      - name: MRSK deploy action step 
        id: mrsk
        uses: ./
        with: 
          args: version